Clubs page
srkpi/sc-kpi-web pull request #111
Opened 2024-09-18 22:09 UTC by Lykhohub

2024-09-18 22:22 UTC, Lykhohub reviewed
.

2024-09-19 14:34 UTC, Markusplay commented
squash all commits into one, and add correct commit messages.

2024-09-19 14:35 UTC, Markusplay commented
remove .idea  files from changes

2024-09-19 14:37 UTC, Markusplay commented
Add Link on Clubs in header. Check design

2024-09-19 14:41 UTC, Markusplay requested changes

2024-09-19 14:41 UTC, Markusplay commented on app/(client)/clubs/page.tsx
> +    setVisibleCount(prevCount => prevCount + 6); // Increase visible clubs by 6
we have 8 clubs per page, fix it and check in other parts

2024-09-19 14:41 UTC, Markusplay commented on app/(client)/clubs/page.tsx
> +            Всі
there is no "Всі" button in design

2024-09-19 14:41 UTC, Markusplay commented on app/(client)/clubs/page.tsx
![image](https://github.com/user-attachments/assets/1cac7d6b-da93-431f-b04e-80db38b655f5)
Page is not adaptive. And You must use another component for filters on mobile

2024-09-19 14:41 UTC, Markusplay commented on components/clubs/club-card.tsx
Check your styles for mobile page, and check the design

2024-10-13 20:52 UTC, Markusplay approved these changes

2024-10-13 20:53 UTC, merged