Footer
srkpi/sc-kpi-web pull request #39
Opened 2024-07-08 20:57 UTC by igaryakqwe

2024-07-09 21:33 UTC, Markusplay requested changes
![image](https://github.com/srkpi/sc-kpi-web/assets/102873980/b66e6507-0d29-4bea-b2a2-752439e93350)
No tg and tt icons on mobile

2024-07-09 21:45 UTC, Markusplay requested changes

2024-07-09 21:45 UTC, Markusplay commented on components/icons/tik-tok.tsx
> +      viewBox="0 0 20 20"
icon's sizes should be flexiable

2024-07-09 21:47 UTC, Markusplay requested changes
Icons on desktop and on moble should have different sizes

2024-07-09 22:00 UTC, Markusplay requested changes

2024-07-09 22:00 UTC, Markusplay commented on components/footer/components/copyrights.tsx
dumb component, return it to footer

2024-07-10 20:14 UTC, igaryakqwe commented
> Icons on desktop and on moble should have different sizes

done

2024-07-10 20:15 UTC, igaryakqwe commented
> ![image](https://private-user-images.githubusercontent.com/102873980/347154784-b66e6507-0d29-4bea-b2a2-752439e93350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDI1NjMsIm5iZiI6MTcyMDY0MjI2MywicGF0aCI6Ii8xMDI4NzM5ODAvMzQ3MTU0Nzg0LWI2NmU2NTA3LTBkMjktNGJlYS1iMmEyLTc1MjQzOWU5MzM1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQyMDExMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2JiM2NhMjZjMjBmYmYyODA4ZGFhYTNjNjhiODhiMjYxNDAzZTE0YTBmZDEwNzJiMGM3ZDdjZWNjYzliYzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-ukFyblqiw5q0PTvsHc32FF-TwoiESWC2FKCBMfXypA) No tg and tt icons on mobile

fixed

2024-07-10 20:52 UTC, Markusplay requested changes
Not adaptive for mobile

2024-07-11 08:10 UTC, Markusplay approved these changes

2024-07-11 08:10 UTC, merged