added error.tsx
srkpi/sc-kpi-web pull request #95
Opened 2024-08-07 09:36 UTC by StepanPotiienko

2024-08-07 12:42 UTC, Markusplay requested changes

2024-08-07 12:42 UTC, Markusplay commented on app/error.tsx
> +              src={'/images/sad_cat.png'}
you don't need curly braces here

2024-08-07 12:42 UTC, Markusplay commented on .json
Delete this file

2024-08-07 12:43 UTC, Markusplay requested changes

2024-08-07 12:43 UTC, Markusplay commented on app/error.tsx
> +};
You don't need to take it to a component. Make all the code in one return

2024-08-07 13:40 UTC, Markusplay requested changes

2024-08-07 13:40 UTC, Markusplay commented on public/images/sad_cat.png
Use HD Gif instead of image

2024-08-07 19:01 UTC, Markusplay requested changes

2024-08-08 03:53 UTC, StepanPotiienko commented on app/error.tsx
> +          <div className="w-full flex flex-row items-center max-[1280px]:h-screen">
We do, because later we add "flex-col" for mobile devices.

2024-08-08 09:41 UTC, Markusplay approved these changes

2024-08-08 09:43 UTC, merged